import math
import pandas as pd
from pandas import ExcelFile
import cufflinks as cf
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
import numpy as np
import datetime

label = ['AAA','AAM','AAT','ABR','ABS','ABT','ACB','ACC','ACL','ADG','ADS','AGG','AGM','AGR','AMD','ANV','APC','APG','APH','ASG'
,'ASM','ASP','AST','BAF','BBC','BCE','BCG','BCM','BFC','BHN','BIC','BID','BKG','BMC','BMI','BMP','BRC','BSI','BTP','BTT','BVH','BWE','C32'
,'C47','CAV','CCI','CCL','CDC','CHP','CIG','CII','CKG','CLC','CLL','CLW','CMG','CMV','CMX','CNG','COM','CRC','CRE','CSM','CSV','CTD','CTF'
,'CTG','CTI','CTR','CVT','D2D','DAG','DAH','DAT','DBC','DBT','DC4','DCL','DCM','DGC','DGW','DHA','DHC','DHG','DHM','DIG','DLG','DMC','DPG'
,'DQC','DRC','DRH','DRL','DSN','DTA','DTL','DTT','DVP','DXG','DXS','DXV','EIB','ELC','EMC','EVE','EVF','EVG','FMC','FPT','FRT','FTS'
,'GAB','GAS','GDT','GEG','GEX','GIL','GMD','GSP','GTA','GVR','HAG','HAH','HAI','HAP','HAR','HAS','HAX','HBC','HCD','HCM','HDB','HDC','HDG'
,'HHP','HHS','HID','HII','HMC','HNG','HOT','HPG','HPX','HQC','HRC','HSG','HSL','HT1','HTI','HTL','HTN','HTV','HU1','HU3','HUB','HVH'
,'HVX','IBC','ICT','IDI','IJC','ILB','IMP','ITA','ITC','ITD','JVC','KBC','KDC','KHG','KHP','KMR','KOS','KPF','KSB','L10','LAF','LBM','LCG'
,'LDG','LGL','LHG','LIX','LM8','LPB','LSS','MBB','MCG','MCP','MDG','MHC','MIG','MSB','MSH','MSN','MWG','NAF','NAV','NCT','NHA','NHH'
,'NHT','NKG','NLG','NNC','NSC','NT2','NTL','NVL','NVT','OCB','OGC','OPC','ORS','PAC','PAN','PC1','PDN','PDR','PET','PGC','PGD','PGI','PGV'
,'PHC','PHR','PIT','PJT','PLP','PLX','PMG','PNC','PNJ','POM','POW','PPC','PSH','PTB','PTC','PTL','PVD','PVT','QBS','QCG','RAL','RDP','REE'
,'S4A','SAB','SAM','SAV','SBA','SBT','SBV','SC5','SCD','SCR','SCS','SFC','SFG','SFI','SGN','SGR','SGT','SHA','SHB','SHI','SHP','SII','SJD'
,'SJF','SJS','SKG','SMA','SMB','SMC','SPM','SRC','SRF','SSB','SSC','SSI','ST8','STG','STK','SVC','SVD','SVI','SVT','SZC','SZL','TBC','TCB'
,'TCD','TCH','TCL','TCM','TCO','TCR','TCT','TDC','TDG','TDH','TDM','TDP','TDW','TEG','TGG','THG','THI','TIP','TIX','TLD','TLG','TLH','TMP'
,'TMS','TMT','TN1','TNA','TNC','TNH','TNI','TNT','TPB','TPC','TRA','TRC','TSC','TTA','TTB','VJC','VMD','VND','VNE','VNG','VNL','VNM','VNS'
,'VOS','VPB','VPD','VPH','VPI','VPS','VRC','VRE','VSC','VSH','VSI','VTB','VTO','YBM']

AAA = pd.read_excel('stock data\AAA Historical Data.xlsx')
AAM = pd.read_excel('stock data\AAM Historical Data.xlsx')
AAT = pd.read_excel('stock data\AAT Historical Data.xlsx')
ABR = pd.read_excel('stock data\ABR Historical Data.xlsx')
ABS = pd.read_excel('stock data\ABS Historical Data.xlsx')
ABT = pd.read_excel('stock data\ABT Historical Data.xlsx')
ACB = pd.read_excel('stock data\ACB Historical Data.xlsx')
ACC = pd.read_excel('stock data\ACC Historical Data.xlsx')
ACL = pd.read_excel('stock data\ACL Historical Data.xlsx')
ADG = pd.read_excel('stock data\ADG Historical Data.xlsx')
ADS = pd.read_excel('stock data\ADS Historical Data.xlsx')
AGG = pd.read_excel('stock data\AGG Historical Data.xlsx')
AGM = pd.read_excel('stock data\AGM Historical Data.xlsx')
AGR = pd.read_excel('stock data\AGR Historical Data.xlsx')
AMD = pd.read_excel('stock data\AMD Historical Data.xlsx')
ANV = pd.read_excel('stock data\ANV Historical Data.xlsx')
APC = pd.read_excel('stock data\APC Historical Data.xlsx')
APC = pd.read_excel('stock data\APC Historical Data.xlsx')
APG = pd.read_excel('stock data\APG Historical Data.xlsx')
APH = pd.read_excel('stock data\APH Historical Data.xlsx')
ASG = pd.read_excel('stock data\ASG Historical Data.xlsx')
ASG = pd.read_excel('stock data\ASG Historical Data.xlsx')
ASM = pd.read_excel('stock data\ASM Historical Data.xlsx')
ASP = pd.read_excel('stock data\ASP Historical Data.xlsx')
AST = pd.read_excel('stock data\AST Historical Data.xlsx')
BAF = pd.read_excel('stock data\BAF Historical Data.xlsx')
BBC = pd.read_excel('stock data\BBC Historical Data.xlsx')
BCE = pd.read_excel('stock data\BCE Historical Data.xlsx')
BCG = pd.read_excel('stock data\BCG Historical Data.xlsx')
BCM = pd.read_excel('stock data\BCM Historical Data.xlsx')
BFC = pd.read_excel('stock data\BFC Historical Data.xlsx')
BHN = pd.read_excel('stock data\BHN Historical Data.xlsx')
BIC = pd.read_excel('stock data\BIC Historical Data.xlsx')
BID = pd.read_excel('stock data\BID Historical Data.xlsx')
BKG = pd.read_excel('stock data\BKG Historical Data.xlsx')
BMC = pd.read_excel('stock data\BMC Historical Data.xlsx')
BMI = pd.read_excel('stock data\BMI Historical Data.xlsx')
BMP = pd.read_excel('stock data\BMP Historical Data.xlsx')
BRC = pd.read_excel('stock data\BRC Historical Data.xlsx')
BSI = pd.read_excel('stock data\BSI Historical Data.xlsx')
BTP = pd.read_excel('stock data\BTP Historical Data.xlsx')
BTT = pd.read_excel('stock data\BTT Historical Data.xlsx')
BVH = pd.read_excel('stock data\BVH Historical Data.xlsx')
BWE = pd.read_excel('stock data\BWE Historical Data.xlsx')
C32 = pd.read_excel('stock data\C32 Historical Data.xlsx')
C47 = pd.read_excel('stock data\C47 Historical Data.xlsx')
CAV = pd.read_excel('stock data\CAV Historical Data.xlsx')
CCI = pd.read_excel('stock data\CCI Historical Data.xlsx')
CCL = pd.read_excel('stock data\CCL Historical Data.xlsx')
CDC = pd.read_excel('stock data\CDC Historical Data.xlsx')
CHP = pd.read_excel('stock data\CHP Historical Data.xlsx')
CIG = pd.read_excel('stock data\CIG Historical Data.xlsx')
CII = pd.read_excel('stock data\CII Historical Data.xlsx')
CKG = pd.read_excel('stock data\CKG Historical Data.xlsx')
CLC = pd.read_excel('stock data\CLC Historical Data.xlsx')
CLL = pd.read_excel('stock data\CLL Historical Data.xlsx')
CLW = pd.read_excel('stock data\CLW Historical Data.xlsx')
CMG = pd.read_excel('stock data\CMG Historical Data.xlsx')
CMV = pd.read_excel('stock data\CMV Historical Data.xlsx')
CMX = pd.read_excel('stock data\CMX Historical Data.xlsx')
CNG = pd.read_excel('stock data\CNG Historical Data.xlsx')
COM = pd.read_excel('stock data\COM Historical Data.xlsx')
CRC = pd.read_excel('stock data\CRC Historical Data.xlsx')
CRE = pd.read_excel('stock data\CRE Historical Data.xlsx')
CSM = pd.read_excel('stock data\CSM Historical Data.xlsx')
CSV = pd.read_excel('stock data\CSV Historical Data.xlsx')
CTD = pd.read_excel('stock data\CTD Historical Data.xlsx')
CTF = pd.read_excel('stock data\CTF Historical Data.xlsx')
CTG = pd.read_excel('stock data\CTG Historical Data.xlsx')
CTI = pd.read_excel('stock data\CTI Historical Data.xlsx')
CTR = pd.read_excel('stock data\CTR Historical Data.xlsx')
CVT = pd.read_excel('stock data\CVT Historical Data.xlsx')
D2D = pd.read_excel('stock data\D2D Historical Data.xlsx')
DAG = pd.read_excel('stock data\DAG Historical Data.xlsx')
DAH = pd.read_excel('stock data\DAH Historical Data.xlsx')
DAT = pd.read_excel('stock data\DAT Historical Data.xlsx')
DBC = pd.read_excel('stock data\DBC Historical Data.xlsx')
DBT = pd.read_excel('stock data\DBT Historical Data.xlsx')
DC4 = pd.read_excel('stock data\DC4 Historical Data.xlsx')
DCL = pd.read_excel('stock data\DCL Historical Data.xlsx')
DCM = pd.read_excel('stock data\DCM Historical Data.xlsx')
DGC = pd.read_excel('stock data\DGC Historical Data.xlsx')
DGW = pd.read_excel('stock data\DGW Historical Data.xlsx')
DHA = pd.read_excel('stock data\DHA Historical Data.xlsx')
DHC = pd.read_excel('stock data\DHC Historical Data.xlsx')
DHG = pd.read_excel('stock data\DHG Historical Data.xlsx')
DHM = pd.read_excel('stock data\DHM Historical Data.xlsx')
DIG = pd.read_excel('stock data\DIG Historical Data.xlsx')
DLG = pd.read_excel('stock data\DLG Historical Data.xlsx')
DMC = pd.read_excel('stock data\DMC Historical Data.xlsx')
DPG = pd.read_excel('stock data\DPG Historical Data.xlsx')
DQC = pd.read_excel('stock data\DQC Historical Data.xlsx')
DRC = pd.read_excel('stock data\DRC Historical Data.xlsx')
DRH = pd.read_excel('stock data\DRH Historical Data.xlsx')
DRL = pd.read_excel('stock data\DRL Historical Data.xlsx')
DSN = pd.read_excel('stock data\DSN Historical Data.xlsx')
DTA = pd.read_excel('stock data\DTA Historical Data.xlsx')
DTL = pd.read_excel('stock data\DTL Historical Data.xlsx')
DTT = pd.read_excel('stock data\DTT Historical Data.xlsx')
DVP = pd.read_excel('stock data\DVP Historical Data.xlsx')
DXG = pd.read_excel('stock data\DXG Historical Data.xlsx')
DXS = pd.read_excel('stock data\DXS Historical Data.xlsx')
DXV = pd.read_excel('stock data\DXV Historical Data.xlsx')
EIB = pd.read_excel('stock data\EIB Historical Data.xlsx')
ELC = pd.read_excel('stock data\ELC Historical Data.xlsx')
EMC = pd.read_excel('stock data\EMC Historical Data.xlsx')
EVE = pd.read_excel('stock data\EVE Historical Data.xlsx')
EVF = pd.read_excel('stock data\EVF Historical Data.xlsx')
EVG = pd.read_excel('stock data\EVG Historical Data.xlsx')
FMC = pd.read_excel('stock data\FMC Historical Data.xlsx')
FMC = pd.read_excel('stock data\FMC Historical Data.xlsx')
FPT = pd.read_excel('stock data\\FPT Historical Data.xlsx')
FRT = pd.read_excel('stock data\FRT Historical Data.xlsx')
FTS = pd.read_excel('stock data\FTS Historical Data.xlsx')
GAB = pd.read_excel('stock data\GAB Historical Data.xlsx')
GAS = pd.read_excel('stock data\GAS Historical Data.xlsx')
GDT = pd.read_excel('stock data\GDT Historical Data.xlsx')
GEG = pd.read_excel('stock data\GEG Historical Data.xlsx')
GEX = pd.read_excel('stock data\GEX Historical Data.xlsx')
GIL = pd.read_excel('stock data\GIL Historical Data.xlsx')
GMD = pd.read_excel('stock data\GMD Historical Data.xlsx')
GSP = pd.read_excel('stock data\GSP Historical Data.xlsx')
GTA = pd.read_excel('stock data\GTA Historical Data.xlsx')
GVR = pd.read_excel('stock data\GVR Historical Data.xlsx')
HAG = pd.read_excel('stock data\HAG Historical Data.xlsx')
HAH = pd.read_excel('stock data\HAH Historical Data.xlsx')
HAI = pd.read_excel('stock data\HAI Historical Data.xlsx')
HAP = pd.read_excel('stock data\HAP Historical Data.xlsx')
HAR = pd.read_excel('stock data\HAR Historical Data.xlsx')
HAS = pd.read_excel('stock data\HAS Historical Data.xlsx')
HAX = pd.read_excel('stock data\HAX Historical Data.xlsx')
HBC = pd.read_excel('stock data\HBC Historical Data.xlsx')
HCD = pd.read_excel('stock data\HCD Historical Data.xlsx')
HCM = pd.read_excel('stock data\HCM Historical Data.xlsx')
HDB = pd.read_excel('stock data\HDB Historical Data.xlsx')
HDC = pd.read_excel('stock data\HDC Historical Data.xlsx')
HDG = pd.read_excel('stock data\HDG Historical Data.xlsx')
HHP = pd.read_excel('stock data\HHP Historical Data.xlsx')
HHS = pd.read_excel('stock data\HHS Historical Data.xlsx')
HID = pd.read_excel('stock data\HID Historical Data.xlsx')
HII = pd.read_excel('stock data\HII Historical Data.xlsx')
HMC = pd.read_excel('stock data\HMC Historical Data.xlsx')
HNG = pd.read_excel('stock data\HNG Historical Data.xlsx')
HOT = pd.read_excel('stock data\HOT Historical Data.xlsx')
HPG = pd.read_excel('stock data\HPG Historical Data.xlsx')
HPX = pd.read_excel('stock data\HPX Historical Data.xlsx')
HQC = pd.read_excel('stock data\HQC Historical Data.xlsx')
HRC = pd.read_excel('stock data\HRC Historical Data.xlsx')
HSG = pd.read_excel('stock data\HSG Historical Data.xlsx')
HSL = pd.read_excel('stock data\HSL Historical Data.xlsx')
HT1 = pd.read_excel('stock data\HT1 Historical Data.xlsx')
HTI = pd.read_excel('stock data\HTI Historical Data.xlsx')
HTL = pd.read_excel('stock data\HTL Historical Data.xlsx')
HTN = pd.read_excel('stock data\HTN Historical Data.xlsx')
HTV = pd.read_excel('stock data\HTV Historical Data.xlsx')
HU1 = pd.read_excel('stock data\HU1 Historical Data.xlsx')
HU3 = pd.read_excel('stock data\HU3 Historical Data.xlsx')
HUB = pd.read_excel('stock data\HUB Historical Data.xlsx')
HVH = pd.read_excel('stock data\HVH Historical Data.xlsx')
HVX = pd.read_excel('stock data\HVX Historical Data.xlsx')
IBC = pd.read_excel('stock data\IBC Historical Data.xlsx')
ICT = pd.read_excel('stock data\ICT Historical Data.xlsx')
IDI = pd.read_excel('stock data\IDI Historical Data.xlsx')
IJC = pd.read_excel('stock data\IJC Historical Data.xlsx')
ILB = pd.read_excel('stock data\ILB Historical Data.xlsx')
IMP = pd.read_excel('stock data\IMP Historical Data.xlsx')
ITA = pd.read_excel('stock data\ITA Historical Data.xlsx')
ITC = pd.read_excel('stock data\ITC Historical Data.xlsx')
ITD = pd.read_excel('stock data\ITD Historical Data.xlsx')
JVC = pd.read_excel('stock data\JVC Historical Data.xlsx')
KBC = pd.read_excel('stock data\KBC Historical Data.xlsx')
KDC = pd.read_excel('stock data\KDC Historical Data.xlsx')
KHG = pd.read_excel('stock data\KHG Historical Data.xlsx')
KHP = pd.read_excel('stock data\KHP Historical Data.xlsx')
KMR = pd.read_excel('stock data\KMR Historical Data.xlsx')
KOS = pd.read_excel('stock data\KOS Historical Data.xlsx')
KPF = pd.read_excel('stock data\KPF Historical Data.xlsx')
KSB = pd.read_excel('stock data\KSB Historical Data.xlsx')
L10 = pd.read_excel('stock data\L10 Historical Data.xlsx')
LAF = pd.read_excel('stock data\LAF Historical Data.xlsx')
LBM = pd.read_excel('stock data\LBM Historical Data.xlsx')
LCG = pd.read_excel('stock data\LCG Historical Data.xlsx')
LDG = pd.read_excel('stock data\LDG Historical Data.xlsx')
LGL = pd.read_excel('stock data\LGL Historical Data.xlsx')
LHG = pd.read_excel('stock data\LHG Historical Data.xlsx')
LIX = pd.read_excel('stock data\LIX Historical Data.xlsx')
LM8 = pd.read_excel('stock data\LM8 Historical Data.xlsx')
LPB = pd.read_excel('stock data\LPB Historical Data.xlsx')
LSS = pd.read_excel('stock data\LSS Historical Data.xlsx')
MBB = pd.read_excel('stock data\MBB Historical Data.xlsx')
MCG = pd.read_excel('stock data\MCG Historical Data.xlsx')
MCP = pd.read_excel('stock data\MCP Historical Data.xlsx')
MDG = pd.read_excel('stock data\MDG Historical Data.xlsx')
MHC = pd.read_excel('stock data\MHC Historical Data.xlsx')
MIG = pd.read_excel('stock data\MIG Historical Data.xlsx')
MSB = pd.read_excel('stock data\MSB Historical Data.xlsx')
MSH = pd.read_excel('stock data\MSH Historical Data.xlsx')
MSN = pd.read_excel('stock data\MSN Historical Data.xlsx')
MWG = pd.read_excel('stock data\MWG Historical Data.xlsx')
NAF = pd.read_excel('stock data\\NAF Historical Data.xlsx')
NAV = pd.read_excel('stock data\\NAV Historical Data.xlsx')
NCT = pd.read_excel('stock data\\NCT Historical Data.xlsx')
NHA = pd.read_excel('stock data\\NHA Historical Data.xlsx')
NHH = pd.read_excel('stock data\\NHH Historical Data.xlsx')
NHT = pd.read_excel('stock data\\NHT Historical Data.xlsx')
NKG = pd.read_excel('stock data\\NKG Historical Data.xlsx')
NLG = pd.read_excel('stock data\\NLG Historical Data.xlsx')
NNC = pd.read_excel('stock data\\NNC Historical Data.xlsx')
NSC = pd.read_excel('stock data\\NSC Historical Data.xlsx')
NT2 = pd.read_excel('stock data\\NT2 Historical Data.xlsx')
NTL = pd.read_excel('stock data\\NTL Historical Data.xlsx')
NVL = pd.read_excel('stock data\\NVL Historical Data.xlsx')
NVT = pd.read_excel('stock data\\NVT Historical Data.xlsx')
OCB = pd.read_excel('stock data\OCB Historical Data.xlsx')
OGC = pd.read_excel('stock data\OGC Historical Data.xlsx')
OPC = pd.read_excel('stock data\OPC Historical Data.xlsx')
ORS = pd.read_excel('stock data\ORS Historical Data.xlsx')
PAC = pd.read_excel('stock data\PAC Historical Data.xlsx')
PAN = pd.read_excel('stock data\PAN Historical Data.xlsx')
PC1 = pd.read_excel('stock data\PC1 Historical Data.xlsx')
PDN = pd.read_excel('stock data\PDN Historical Data.xlsx')
PDR = pd.read_excel('stock data\PDR Historical Data.xlsx')
PET = pd.read_excel('stock data\PET Historical Data.xlsx')
PGC = pd.read_excel('stock data\PGC Historical Data.xlsx')
PGD = pd.read_excel('stock data\PGD Historical Data.xlsx')
PGI = pd.read_excel('stock data\PGI Historical Data.xlsx')
PGV = pd.read_excel('stock data\PGV Historical Data.xlsx')
PHC = pd.read_excel('stock data\PHC Historical Data.xlsx')
PHR = pd.read_excel('stock data\PHR Historical Data.xlsx')
PIT = pd.read_excel('stock data\PIT Historical Data.xlsx')
PJT = pd.read_excel('stock data\PJT Historical Data.xlsx')
PLP = pd.read_excel('stock data\PLP Historical Data.xlsx')
PLX = pd.read_excel('stock data\PLX Historical Data.xlsx')
PMG = pd.read_excel('stock data\PMG Historical Data.xlsx')
PNC = pd.read_excel('stock data\PNC Historical Data.xlsx')
PNJ = pd.read_excel('stock data\PNJ Historical Data.xlsx')
POM = pd.read_excel('stock data\POM Historical Data.xlsx')
POW = pd.read_excel('stock data\POW Historical Data.xlsx')
PPC = pd.read_excel('stock data\PPC Historical Data.xlsx')
PSH = pd.read_excel('stock data\PSH Historical Data.xlsx')
PTB = pd.read_excel('stock data\PTB Historical Data.xlsx')
PTC = pd.read_excel('stock data\PTC Historical Data.xlsx')
PTL = pd.read_excel('stock data\PTL Historical Data.xlsx')
PVD = pd.read_excel('stock data\PVD Historical Data.xlsx')
PVT = pd.read_excel('stock data\PVT Historical Data.xlsx')
QBS = pd.read_excel('stock data\QBS Historical Data.xlsx')
QCG = pd.read_excel('stock data\QCG Historical Data.xlsx')
RAL = pd.read_excel('stock data\RAL Historical Data.xlsx')
RDP = pd.read_excel('stock data\RDP Historical Data.xlsx')
REE = pd.read_excel('stock data\REE Historical Data.xlsx')
S4A = pd.read_excel('stock data\S4A Historical Data.xlsx')
SAB = pd.read_excel('stock data\SAB Historical Data.xlsx')
SAM = pd.read_excel('stock data\SAM Historical Data.xlsx')
SAV = pd.read_excel('stock data\SAV Historical Data.xlsx')
SBA = pd.read_excel('stock data\SBA Historical Data.xlsx')
SBT = pd.read_excel('stock data\SBT Historical Data.xlsx')
SBV = pd.read_excel('stock data\SBV Historical Data.xlsx')
SC5 = pd.read_excel('stock data\SC5 Historical Data.xlsx')
SCD = pd.read_excel('stock data\SCD Historical Data.xlsx')
SCR = pd.read_excel('stock data\SCR Historical Data.xlsx')
SCS = pd.read_excel('stock data\SCS Historical Data.xlsx')
SFC = pd.read_excel('stock data\SFC Historical Data.xlsx')
SFG = pd.read_excel('stock data\SFG Historical Data.xlsx')
SFI = pd.read_excel('stock data\SFI Historical Data.xlsx')
SGN = pd.read_excel('stock data\SGN Historical Data.xlsx')
SGR = pd.read_excel('stock data\SGR Historical Data.xlsx')
SGT = pd.read_excel('stock data\SGT Historical Data.xlsx')
SHA = pd.read_excel('stock data\SHA Historical Data.xlsx')
SHB = pd.read_excel('stock data\SHB Historical Data.xlsx')
SHI = pd.read_excel('stock data\SHI Historical Data.xlsx')
SHP = pd.read_excel('stock data\SHP Historical Data.xlsx')
SII = pd.read_excel('stock data\SII Historical Data.xlsx')
SJD = pd.read_excel('stock data\SJD Historical Data.xlsx')
SJF = pd.read_excel('stock data\SJF Historical Data.xlsx')
SJS = pd.read_excel('stock data\SJS Historical Data.xlsx')
SKG = pd.read_excel('stock data\SKG Historical Data.xlsx')
SMA = pd.read_excel('stock data\SMA Historical Data.xlsx')
SMB = pd.read_excel('stock data\SMB Historical Data.xlsx')
SMC = pd.read_excel('stock data\SMC Historical Data.xlsx')
SPM = pd.read_excel('stock data\SPM Historical Data.xlsx')
SRC = pd.read_excel('stock data\SRC Historical Data.xlsx')
SRF = pd.read_excel('stock data\SRF Historical Data.xlsx')
SSB = pd.read_excel('stock data\SSB Historical Data.xlsx')
SSC = pd.read_excel('stock data\SSC Historical Data.xlsx')
SSI = pd.read_excel('stock data\SSI Historical Data.xlsx')
ST8 = pd.read_excel('stock data\ST8 Historical Data.xlsx')
STG = pd.read_excel('stock data\STG Historical Data.xlsx')
STK = pd.read_excel('stock data\STK Historical Data.xlsx')
SVC = pd.read_excel('stock data\SVC Historical Data.xlsx')
SVD = pd.read_excel('stock data\SVD Historical Data.xlsx')
SVI = pd.read_excel('stock data\SVI Historical Data.xlsx')
SVT = pd.read_excel('stock data\SVT Historical Data.xlsx')
SZC = pd.read_excel('stock data\SZC Historical Data.xlsx')
SZL = pd.read_excel('stock data\SZL Historical Data.xlsx')
TBC = pd.read_excel('stock data\TBC Historical Data.xlsx')
TCB = pd.read_excel('stock data\TCB Historical Data.xlsx')
TCD = pd.read_excel('stock data\TCD Historical Data.xlsx')
TCH = pd.read_excel('stock data\TCH Historical Data.xlsx')
TCL = pd.read_excel('stock data\TCL Historical Data.xlsx')
TCM = pd.read_excel('stock data\TCM Historical Data.xlsx')
TCO = pd.read_excel('stock data\TCO Historical Data.xlsx')
TCR = pd.read_excel('stock data\TCR Historical Data.xlsx')
TCT = pd.read_excel('stock data\TCT Historical Data.xlsx')
TDC = pd.read_excel('stock data\TDC Historical Data.xlsx')
TDG = pd.read_excel('stock data\TDG Historical Data.xlsx')
TDH = pd.read_excel('stock data\TDH Historical Data.xlsx')
TDM = pd.read_excel('stock data\TDM Historical Data.xlsx')
TDP = pd.read_excel('stock data\TDP Historical Data.xlsx')
TDW = pd.read_excel('stock data\TDW Historical Data.xlsx')
TEG = pd.read_excel('stock data\TEG Historical Data.xlsx')
TGG = pd.read_excel('stock data\TGG Historical Data.xlsx')
THG = pd.read_excel('stock data\THG Historical Data.xlsx')
THI = pd.read_excel('stock data\THI Historical Data.xlsx')
TIP = pd.read_excel('stock data\TIP Historical Data.xlsx')
TIX = pd.read_excel('stock data\TIX Historical Data.xlsx')
TLD = pd.read_excel('stock data\TLD Historical Data.xlsx')
TLG = pd.read_excel('stock data\TLG Historical Data.xlsx')
TLH = pd.read_excel('stock data\TLH Historical Data.xlsx')
TMP = pd.read_excel('stock data\TMP Historical Data.xlsx')
TMS = pd.read_excel('stock data\TMS Historical Data.xlsx')
TMT = pd.read_excel('stock data\TMT Historical Data.xlsx')
TN1 = pd.read_excel('stock data\TN1 Historical Data.xlsx')
TNA = pd.read_excel('stock data\TNA Historical Data.xlsx')
TNC = pd.read_excel('stock data\TNC Historical Data.xlsx')
TNH = pd.read_excel('stock data\TNH Historical Data.xlsx')
TNI = pd.read_excel('stock data\TNI Historical Data.xlsx')
TNT = pd.read_excel('stock data\TNT Historical Data.xlsx')
TPB = pd.read_excel('stock data\TPB Historical Data.xlsx')
TPC = pd.read_excel('stock data\TPC Historical Data.xlsx')
TRA = pd.read_excel('stock data\TRA Historical Data.xlsx')
TRC = pd.read_excel('stock data\TRC Historical Data.xlsx')
TSC = pd.read_excel('stock data\TSC Historical Data.xlsx')
TTA = pd.read_excel('stock data\TTA Historical Data.xlsx')
TTB = pd.read_excel('stock data\TTB Historical Data.xlsx')
VJC = pd.read_excel('stock data\VJC Historical Data.xlsx')
VMD = pd.read_excel('stock data\VMD Historical Data.xlsx')
VND = pd.read_excel('stock data\VND Historical Data.xlsx')
VNE = pd.read_excel('stock data\VNE Historical Data.xlsx')
VNG = pd.read_excel('stock data\VNG Historical Data.xlsx')
VNL = pd.read_excel('stock data\VNL Historical Data.xlsx')
VNM = pd.read_excel('stock data\VNM Historical Data.xlsx')
VNS = pd.read_excel('stock data\VNS Historical Data.xlsx')
VOS = pd.read_excel('stock data\VOS Historical Data.xlsx')
VPB = pd.read_excel('stock data\VPB Historical Data.xlsx')
VPD = pd.read_excel('stock data\VPD Historical Data.xlsx')
VPH = pd.read_excel('stock data\VPH Historical Data.xlsx')
VPI = pd.read_excel('stock data\VPI Historical Data.xlsx')
VPS = pd.read_excel('stock data\VPS Historical Data.xlsx')
VRC = pd.read_excel('stock data\VRC Historical Data.xlsx')
VRE = pd.read_excel('stock data\VRE Historical Data.xlsx')
VSC = pd.read_excel('stock data\VSC Historical Data.xlsx')
VSH = pd.read_excel('stock data\VSH Historical Data.xlsx')
VSI = pd.read_excel('stock data\VSI Historical Data.xlsx')
VTB = pd.read_excel('stock data\VTB Historical Data.xlsx')
VTO = pd.read_excel('stock data\VTO Historical Data.xlsx')
YBM = pd.read_excel('stock data\YBM Historical Data.xlsx')
YEG = pd.read_excel('stock data\YEG Historical Data.xlsx')
VNINDEX = pd.read_excel('VNINDEX Historical Data_excel.xlsx')

stocks = pd.concat([AAA, AAM, AAT, ABR, ABS, ABT, ACB, ACC, ACL, ADG, ADS, AGG, AGM, AGR, AMD, ANV, APC, APG, APH, ASG, ASM, ASP, AST, BAF, 
BBC, BCE, BCG, BCM, BFC, BHN, BIC, BID, BKG, BMC, BMI, BMP, BRC, BSI, BTP, BTT, BVH, BWE, C32, C47, CAV, CCI, CCL, CDC, CHP, CIG, CII, CKG,
CLC, CLL, CLW, CMG, CMV, CMX, CNG, COM, CRC, CRE, CSM, CSV, CTD, CTF, CTG, CTI, CTR, CVT, D2D, DAG, DAH, DAT, DBC, DBT, DC4, DCL, DCM, DGC,
DGW, DHA, DHC, DHG, DHM, DIG, DLG, DMC, DPG, DQC, DRC, DRH, DRL, DSN, DTA, DTL, DTT, DVP, DXG, DXS, DXV, EIB, ELC, EMC, EVE, EVF, EVG, FMC,
FPT, FRT, FTS, GAB, GAS, GDT, GEG, GEX, GIL, GMD, GSP, GTA, GVR, HAG, HAH, HAI, HAP, HAR, HAS, HAX, HBC, HCD, HCM, HDB, HDC, HDG, HHP, HHS,
HID, HII, HMC, HNG, HOT, HPG, HPX, HQC, HRC, HSG, HSL, HT1, HTI, HTL, HTN, HTV, HU1, HU3, HUB, HVH, HVX, IBC, ICT, IDI, IJC, ILB, IMP, ITA,
ITC, ITD, JVC, KBC, KDC, KHG, KHP, KMR, KOS, KPF, KSB, L10, LAF, LBM, LCG, LDG, LGL, LHG, LIX, LM8, LPB, LSS, MBB, MCG, MCP, MDG, MHC, MIG,
MSB, MSH, MSN, MWG, NAF, NAV, NCT, NHA, NHH, NHT, NKG, NLG, NNC, NSC, NT2, NTL, NVL, NVT, OCB, OGC, OPC, ORS, PAC, PAN, PC1, PDN, PDR, PET,
PGC, PGD, PGI, PGV, PHC, PHR, PIT, PJT, PLP, PLX, PMG, PNC, PNJ, POM, POW, PPC, PSH, PTB, PTC, PTL, PVD, PVT, QBS, QCG, RAL, RDP, REE, S4A,
SAB, SAM, SAV, SBA, SBT, SBV, SC5, SCD, SCR, SCS, SFC, SFG, SFI, SGN, SGR, SGT, SHA, SHB, SHI, SHP, SII, SJD, SJF, SJS, SKG, SMA, SMB, SMC,
SPM, SRC, SRF, SSB, SSC, SSI, ST8, STG, STK, SVC, SVD, SVI, SVT, SZC, SZL, TBC, TCB, TCD, TCH, TCL, TCM, TCO, TCR, TCT, TDC, TDG, TDH, TDM, 
TDP, TDW, TEG, TGG, THG, THI, TIP, TIX, TLD, TLG, TLH, TMP, TMS, TMT, TN1, TNA, TNC, TNH, TNI, TNT, TPB, TPC, TRA, TRC, TSC, TTA, TTB, VJC, 
VMD, VND, VNE, VNG, VNL, VNM, VNS, VOS, VPB, VPD, VPH, VPI, VPS, VRC, VRE, VSC, VSH, VSI, VTB, VTO, YBM],axis=1, keys = label)
stocks.to_csv('stocks.csv', header=True, index=False, encoding='utf-8')